[tool.poetry]
name = "circuit-puzzles"
packages = [{include = "circuit_puzzles"}]
version = "1.3.0"
description = "Puzzles powering Circuit Protocol - a decentralized stablecoin and lending system on the Chia blockchain that enables permissionless borrowing of BYC against XCH collateral"
authors = ["Sebastjan Trepca <set@circuitdao.com>", "Nic Niedermowwe <nin@circuitdao.com>"]
exclude = [
    "circuit_puzzles/*.clsp",
    "circuit_puzzles/*.clib"
]

[tool.poetry.dependencies]
python = ">=3.11"
chialisp = "^0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"