[tool.poetry]
name = "circuit-puzzles"
packages = [{include = "circuit_puzzles"}]
version = "1.1.0"
description = "Puzzles used in stablecoin protocol Circuit on Chia blockchain"
authors = ["Sebastjan Trepca <set@circuitdao.com>", "Nic Niedermowwe <nin@circuitdao.com>"]
exclude = [
    "circuit_puzzles/*.clsp",
    "circuit_puzzles/*.clib"
]

[tool.poetry.dependencies]
python = ">=3.11"
chialisp_loader = "^0.1.2"
chialisp_builder = "^0.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
